name: image_editor_platform_interface
publish_to: none
description: Edit your image data and output to file/memory on Android and iOS.
version: 1.0.1
repository: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.1
  plugin_platform_interface: 
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
